version: '3.5'
services:
  terminalserver:
    build: ./
    image: danielguerra/ubuntu-xrdp
    container_name: uxrdp
    hostname: terminalserver
    restart: always
    shm_size: 1g
    environment:
       PASSWORDHASH: $$1$$z53Cg/fV$$06o379IvIOxj/ESruVKrG1
       IDLETIME: 11
    ports:
      - "3389:3389"
      - "2222:22"
    volumes:
      - ssh:/etc/ssh/
      - /home/:/home/
  browser:
    build: .
    image: fphammerle/brave-browser-x11
    environment:
    - DISPLAY
    volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix
    security_opt: [no-new-privileges]

volumes:
  ssh:
